services:
  postgres:
    image: postgres:17
    container_name: ${CONTAINER_NAME:-fip_postgres}
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT1}:${POSTGRES_PORT2}
    volumes:
      #- ./db/reset_customer_layer.sql:/docker-entrypoint-initdb.d/001_reset_customer_layer.sql:ro
      - fip_postgres_data:/var/lib/postgresql/data

volumes:
  fip_postgres_data: