services:
  postgres:
    image: postgres:17
    container_name: fip_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: fip_user
      POSTGRES_PASSWORD: fip_password
      POSTGRES_DB: fip_db
    ports:
      - "5432:5432"
    volumes:
      - fip_postgres_data:/var/lib/postgresql/data

volumes:
  fip_postgres_data: